# general
seed: 42
workers: 8

# train options
batch_size: 128
image_size: 224
start_epoch: 0
epochs: 1200
dataset: "UC-Merced" # / UC-Merced / SIRI-WHU / AID / DTD

# model options
feature_dim: 128
model_path: "save/UC-Merced"
reload: False

# loss options
learning_rate: 0.0003
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
gpu: 0

